name: Test on Feature Branches

on:
  push:
    branches:
      - 'feature/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Merge develop into feature branch
        run: |
          git fetch origin main
          git checkout main       
          git pull origin main    
          git checkout -          
          git merge main || git merge --abort
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm test
